@startuml

' Diagram settings
hide circle
skinparam linetype ortho
skinparam shadowing false
skinparam roundCorner 5
skinparam defaultFontName "Roboto, Helvetica"
skinparam class {
    BackgroundColor PaleGreen
    ArrowColor SeaGreen
    BorderColor SeaGreen
}

' Title
title Entity-Relationship Diagram for Patient/Visitor System

' Entities
entity "User" as user {
  + id: int <<PK>>
  --
  username: varchar(180) <<unique>>
  roles: json
  password: varchar(255)
  name: varchar(255)
}

entity "Patient" as patient {
  + id: int <<PK>>
  --
  file: varchar(12) <<unique>>
  name: varchar(255)
  disability: boolean
}

entity "Visitor" as visitor {
  + id: int <<PK>>
  --
  name: varchar(255)
  phone: varchar(255)
  dni: varchar(255)
  tag: int
  destination: varchar(255)
  check_in_at: datetime
  check_out_at: datetime
  relationship: varchar(255)
  evidence: varchar(255)
}

entity "Appointment" as appointment {
  + id: int <<PK>>
  --
  # patient_id: int <<FK>>
  agenda: varchar(255)
  specialty: varchar(255)
  location: varchar(255)
  date_at: datetime
  type: varchar(255)
  status: varchar(255)
}

entity "Attendance" as attendance {
  + id: int <<PK>>
  --
  # patient_id: int <<FK>>
  check_in_at: datetime
  check_out_at: datetime
  tag: int
  evidence: varchar(255)
}

' Relationships
patient "1" ||--|{ "0..*" appointment : "schedules"
patient "1" ||--|{ "0..*" attendance : "has"
patient "0..*" }o--o{ "0..*" visitor : "is visited by"

@enduml
