@startuml ERD

!theme vibrant
hide circle
skinparam linetype polyline

' Title
title Entity-Relationship Diagram for Patient/Visitor System

entity "User" as user {
  + id: int
  --
  * username: string
  * roles: array
  * password: string
  * name: string
}

entity "Patient" as patient {
  + id: int
  --
  * file: string
  * name: string
  * disability: bool
}

entity "Hospitalized" as hospitalized {
  + id: int
  --
  * service: string
  * bed: string
}

entity "Visitor" as visitor {
  + id: int
  --
  * name: string
  phone: string
  * dni: string
  * tag: int
  * destination: string
  * checkInAt: DateTime
  checkOutAt: DateTime
  relationship: string
  evidence: string
}

entity "Appointment" as appointment {
  + id: int
  --
  * agenda: string
  * specialty: string
  * location: string
  * date_at: DateTime
  * type: string
  * status: string
}

entity "Attendance" as attendance {
  + id: int
  --
  * checkInAt: DateTime
  checkOutAt: DateTime
  * tag: int
  evidence: string
}

' Relationships

user ||--o{ attendance : "checkInUser"
user ||--o{ attendance : "checkOutUser"
user ||--o{ visitor : "checkInUser"
user ||--o{ visitor : "checkOutUser"

patient ||--o{ appointment
patient ||--o{ attendance
patient }o--o{ visitor
patient ||--|| hospitalized

@enduml
