-- patient
INSERT INTO patient (id, file, name, disability) VALUES (1, '000028567', 'BLANDINA HERNANDEZ PAREDES', 0) ON CONFLICT(id) DO UPDATE SET file = excluded.file, name = excluded.name, disability = excluded.disability;
INSERT INTO patient (id, file, name, disability) VALUES (2, '000028878', 'FRANCISCO ARIZA BRAVO', 0) ON CONFLICT(id) DO UPDATE SET file = excluded.file, name = excluded.name, disability = excluded.disability;
INSERT INTO patient (id, file, name, disability) VALUES (3, '000028915', 'JUAN SANTIN ROSEL', 0) ON CONFLICT(id) DO UPDATE SET file = excluded.file, name = excluded.name, disability = excluded.disability;
INSERT INTO patient (id, file, name, disability) VALUES (4, '000028974', 'CARMELO REYES PACHECO', 0) ON CONFLICT(id) DO UPDATE SET file = excluded.file, name = excluded.name, disability = excluded.disability;
INSERT INTO patient (id, file, name, disability) VALUES (5, '000029064', 'ANTONIA LARA HERRERA', 0) ON CONFLICT(id) DO UPDATE SET file = excluded.file, name = excluded.name, disability = excluded.disability;
INSERT INTO patient (id, file, name, disability) VALUES (6, '000029083', 'TELESFORO HERNANDEZ GONZALEZ', 0) ON CONFLICT(id) DO UPDATE SET file = excluded.file, name = excluded.name, disability = excluded.disability;
INSERT INTO patient (id, file, name, disability) VALUES (7, '000029181', 'SILVIA TERESITA FUENTES RIVERA', 0) ON CONFLICT(id) DO UPDATE SET file = excluded.file, name = excluded.name, disability = excluded.disability;
INSERT INTO patient (id, file, name, disability) VALUES (8, '000029212', 'DULCE MARIA BERENICE REZA VERGARA', 0) ON CONFLICT(id) DO UPDATE SET file = excluded.file, name = excluded.name, disability = excluded.disability;
INSERT INTO patient (id, file, name, disability) VALUES (9, '000029630', 'FRANCISCO JAVIER BAEZ ALDAMA', 0) ON CONFLICT(id) DO UPDATE SET file = excluded.file, name = excluded.name, disability = excluded.disability;
INSERT INTO patient (id, file, name, disability) VALUES (10, '000029897', 'ARNULFO DIAZ BARRAGAN', 0) ON CONFLICT(id) DO UPDATE SET file = excluded.file, name = excluded.name, disability = excluded.disability;

-- appointment
INSERT INTO appointment (id, patient_id, place, date_at, type) VALUES (1068560, 117096, 'ALERGOLOGIA C1 - DR. GANDHI', '2032-01-05 10:00:00', 'Cita') ON CONFLICT(id) DO UPDATE SET patient_id = excluded.patient_id, place = excluded.place, date_at = excluded.date_at, type = excluded.type;
INSERT INTO appointment (id, patient_id, place, date_at, type) VALUES (1069399, 150583, 'GERIATRÍA SEGUIMIENTO SARS-COV-2', '2033-01-13 09:00:00', 'Cita') ON CONFLICT(id) DO UPDATE SET patient_id = excluded.patient_id, place = excluded.place, date_at = excluded.date_at, type = excluded.type;
INSERT INTO appointment (id, patient_id, place, date_at, type) VALUES (1071766, 130297, 'ALERGOLOGIA C1 - DR. GANDHI', '2032-01-12 10:00:00', 'Cita') ON CONFLICT(id) DO UPDATE SET patient_id = excluded.patient_id, place = excluded.place, date_at = excluded.date_at, type = excluded.type;
INSERT INTO appointment (id, patient_id, place, date_at, type) VALUES (1071865, 117973, 'ALERGOLOGIA E INMUNOLOGIA C1', '2032-01-28 10:00:00', 'Cita') ON CONFLICT(id) DO UPDATE SET patient_id = excluded.patient_id, place = excluded.place, date_at = excluded.date_at, type = excluded.type;
INSERT INTO appointment (id, patient_id, place, date_at, type) VALUES (1213097, 518444, 'DR. GUSTAVO IVAN CENTENO SAENZ', '2034-01-26 10:30:00', 'Cita') ON CONFLICT(id) DO UPDATE SET patient_id = excluded.patient_id, place = excluded.place, date_at = excluded.date_at, type = excluded.type;
INSERT INTO appointment (id, patient_id, place, date_at, type) VALUES (1320803, 124439, 'TB - DRA. NORMA ANGÉLICA TÉLLEZ NAVARRETE', '2028-06-07 10:00:00', 'Cita') ON CONFLICT(id) DO UPDATE SET patient_id = excluded.patient_id, place = excluded.place, date_at = excluded.date_at, type = excluded.type;
INSERT INTO appointment (id, patient_id, place, date_at, type) VALUES (1329585, 122214, 'AUDIOLOGIA 3 DR. LARA', '2026-01-05 11:00:00', 'Cita') ON CONFLICT(id) DO UPDATE SET patient_id = excluded.patient_id, place = excluded.place, date_at = excluded.date_at, type = excluded.type;
INSERT INTO appointment (id, patient_id, place, date_at, type) VALUES (1335178, 114581, 'CONSULTORIO DEL SUEÑO', '2025-11-28 09:40:00', 'Cita') ON CONFLICT(id) DO UPDATE SET patient_id = excluded.patient_id, place = excluded.place, date_at = excluded.date_at, type = excluded.type;
INSERT INTO appointment (id, patient_id, place, date_at, type) VALUES (1335190, 637821, 'CONSULTORIO DEL SUEÑO', '2025-11-28 09:40:00', 'Cita') ON CONFLICT(id) DO UPDATE SET patient_id = excluded.patient_id, place = excluded.place, date_at = excluded.date_at, type = excluded.type;
INSERT INTO appointment (id, patient_id, place, date_at, type) VALUES (1336738, 666081, 'TELECONSULTA - CONSULTORIO DEL SUEÑO', '2025-11-14 12:00:00', 'Cita') ON CONFLICT(id) DO UPDATE SET patient_id = excluded.patient_id, place = excluded.place, date_at = excluded.date_at, type = excluded.type;
